// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf86Soeu0pVLOX8iibLu6X1Cx2cQ4KlxU',
    appId: '1:1064928420744:web:47420784166b3cac8ed03d',
    messagingSenderId: '1064928420744',
    projectId: 'myapp-a7805',
    authDomain: 'myapp-a7805.firebaseapp.com',
    storageBucket: 'myapp-a7805.firebasestorage.app',
    measurementId: 'G-SVK3L0DPVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxS-_vNmoryxQm3NXl4yygl-fHZmORswY',
    appId: '1:1064928420744:android:67187a7f3702f1a08ed03d',
    messagingSenderId: '1064928420744',
    projectId: 'myapp-a7805',
    storageBucket: 'myapp-a7805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQke_UR1oqg5WRWkNPfuaFTBmAjDbMoVk',
    appId: '1:1064928420744:ios:bc7ea5835731aff28ed03d',
    messagingSenderId: '1064928420744',
    projectId: 'myapp-a7805',
    storageBucket: 'myapp-a7805.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQke_UR1oqg5WRWkNPfuaFTBmAjDbMoVk',
    appId: '1:1064928420744:ios:bc7ea5835731aff28ed03d',
    messagingSenderId: '1064928420744',
    projectId: 'myapp-a7805',
    storageBucket: 'myapp-a7805.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf86Soeu0pVLOX8iibLu6X1Cx2cQ4KlxU',
    appId: '1:1064928420744:web:2ffeb739b3a7f5248ed03d',
    messagingSenderId: '1064928420744',
    projectId: 'myapp-a7805',
    authDomain: 'myapp-a7805.firebaseapp.com',
    storageBucket: 'myapp-a7805.firebasestorage.app',
    measurementId: 'G-ZHDN7HMKW1',
  );
}
